LANGUAGES = {
    'en': {
        'hello': '👋 Hello, {user}!',
        'balance': '💰 Balance: {balance} EUR',
        'overpay': '💳 Send the exact amount. Overpayments will be credited.',
        'shop': '🛍 Shop',
        'profile': '👤 Profile',
        'top_up': '💸 Top Up',
        'channel': '📢 Channel',
        'price_list': '💲 Price List',
        'language': '🌐 Language',
        'admin_panel': '🎛 Admin Panel',
        'help': '❓ Help',
        'help_info': (
            'Use the main menu to work with the bot:\n'
            '🛍 Shop – browse categories and choose a product.\n'
            '   • Select an item and confirm to purchase it.\n'
            '👤 Profile – view your balance and purchased items.\n'
            '💸 Top Up – choose a payment method and follow the instructions to add funds.\n'
            '🌐 Language – switch the interface language.\n'
            '🎁 Purchased items – available in Profile after you buy something.\n'
            'If you need assistance, contact {helper}.'
        ),
        'admin_help_info': (
            'Admin panel functions:\n'
            '🛠 Assign assistants – manage assistant accounts.\n'
            '📦 View Stock – browse and delete available product stock.\n'
            '🏪 Parduotuvės valdymas – manage shop categories and items.\n'
            '👥 Vartotojų valdymas – manage user balances and roles.\n'
            '📢 Pranešimų siuntimas – send messages to all users.'
        ),
        'assistant_help_info': (
            'Assistant panel functions:\n'
            '🖼 Assign photos – attach photos to items.\n'
            'Use Back to menu to return.'
        ),
        'admin_menu_title': '⛩️ Admin menu',
        'assign_photos_menu': '🖼 Assign photos',
        'shop_management_menu': '🏪 Shop management',
        'information_menu_button': 'ℹ️ Information',
        'information_menu_title': 'ℹ️ Information menu',
        'analytics_button': '📊 Analytics',
        'shop_management_title': '⛩️ Shop management',
        'analytics_title': '📊 Analytics overview',
        'analytics_total_revenue': '💰 Total revenue: {amount}€',
        'analytics_chart_header': 'Sales ({label})',
        'analytics_period_daily': 'last 7 days',
        'analytics_period_weekly': 'weekly (4 weeks)',
        'analytics_period_monthly': 'monthly (6 months)',
        'analytics_chart_line': '{period}: {bar} {revenue}€ ({orders} orders)',
        'analytics_no_data': 'No data available yet.',
        'analytics_top_cities_header': '🏙️ Top cities',
        'analytics_unknown_city': 'Unknown city',
        'analytics_city_with_region': '{city} ({region})',
        'analytics_group_line': '{name} — {orders} orders / {revenue}€',
        'analytics_top_types_header': '🏷️ Top product types',
        'analytics_uncategorized': 'Uncategorized',
        'analytics_top_products_header': '🔥 Top products',
        'analytics_activity_header': '👥 User activity',
        'analytics_activity_line_active': '✅ Active users: {count}',
        'analytics_activity_line_inactive': '⚠️ Inactive users: {count}',
        'analytics_button_day': 'Daily',
        'analytics_button_week': 'Weekly',
        'analytics_button_month': 'Monthly',
        'analytics_view_overview': 'Overview',
        'analytics_view_cities': 'Cities',
        'analytics_view_types': 'Product types',
        'analytics_view_products': 'Top products',
        'analytics_view_activity': 'User activity',
        'shop_manage_goods': '📦 Manage goods',
        'shop_manage_categories': '🗂️ Manage categories',
        'shop_manage_promos': '🏷️ Promo codes',
        'shop_manage_resellers': '🤝 Resellers',
        'shop_manage_broadcast': '📢 Broadcasts',
        'shop_manage_stock': '🗄️ Stock tools',
        'shop_manage_assistants': '🛠️ Assistant management',
        'information_users': '👥 User management',
        'information_logs': '📝 Logs',
        'information_statistics': '📊 Statistics',
        'information_purchases': '🛒 Purchases',
        'information_stock': '📦 View stock',
        'menu_lottery': '🎟️ Lottery',
        'menu_reviews': '📝 Reviews',
        'menu_reservations': '🗂️ Reservations',
        'menu_manual_payments': '💳 Manual payments',
        'menu_media': '🖼️ Media library',
        'lottery_view_tickets': '📋 View tickets',
        'lottery_run_action': '🎰 Run lottery',
        'purchase_view_file': '👁 View file',
        'purchases_choose_date': '📅 Select a date',
        'purchases_for_date': '📦 Purchases on {date}',
        'purchase_not_found': 'Purchase not found.',
        'broadcast_segment_all': 'All users',
        'broadcast_segment_active': 'Active users',
        'broadcast_segment_inactive': 'Inactive users',
        'broadcast_segment_no_activity': 'No activity recorded',
        'broadcast_segment_resellers': 'Resellers only',
        'broadcast_segment_city': 'By city',
        'broadcast_segment_region': 'By region',
        'broadcast_choose_segment': 'Choose who should receive the broadcast:',
        'broadcast_prompt_message': 'Send the message you want to broadcast:',
        'broadcast_pick_city': 'Select a city:',
        'broadcast_pick_region': 'Select a region:',
        'broadcast_no_cities': 'No cities configured yet.',
        'broadcast_no_regions': 'No regions configured yet.',
        'broadcast_no_recipients': '❌ No recipients match the selected segment.',
        'broadcast_completed': '✅ Broadcast sent to {count} users.',
        'choose_language': 'Please choose a language',
        'invoice_message': (
            '🧾 <b>Payment Invoice Created</b>\n\n'
            '<b>Amount:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Payment Address:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Expires At:</b> {expires_at} LT\n'
            '⚠️ <b>Payment must be completed within 15 minutes of invoice creation.</b>\n\n'
            '❗️ <b>Important:</b> Send <u>exactly</u> this amount of {currency}.\n\n'
            '✅ <b>Confirmation is automatic via webhook after network confirmation.</b>'
        ),
        'cancel': 'Cancel',
        'cancel_payment': '❌ Cancel Payment',
        'payment_successful': '✅ Payment confirmed. Balance increased by {amount}€',
        'back_home': 'Back Home',
        'invoice_cancelled': 'Payment failed/expired. Your items are no longer reserved.',
        'total_purchases': '📦 Total Purchases: {count}',
        'streak': '🔥 Streak: {days} days',
        'note': '⚠️ Note: No refunds. Please ensure you send the exact amount for payments, as underpayments will not be confirmed.',
        'feature_disabled': '❌ This feature is currently disabled.',
        'rate_experience': '⭐ How was your overall experience?',
        'rate_service': 'How was your experience with the service?',
        'rate_product': 'What is your opinion on the product?',
        'ask_feedback_reason': 'Would you like to tell us why?',
        'feedback_reason': 'Please write your feedback:',
        'thanks_feedback': 'Thanks for your feedback!',
        'confirm_purchase': 'Confirm purchase of {item} for {price}€?',
        'purchase_button': 'Purchase',
        'apply_promo': 'Apply promo code',
        'promo_prompt': 'Send promo code:',
        'promo_invalid': '❌ Invalid or expired promo code',
        'promo_applied': '✅ Promo code applied. New price: {price}€',
        'yes': '✅ Yes',
        'no': '❌ No',
        'confirm': '✅ Confirm',
        'rerun': '🔄 Rerun',
        'assign_more': '✅ Photo assigned. Add another?',
        'purchased_items': '📦 Purchased items',
        'purchased_items': '🎁 Purchased items',
        'back_to_menu': '🔙 Back to menu',
        'users_tickets': '🎟️ User tickets:',
        'no_tickets': 'No tickets',
        'lottery_winner': '🎉 Winner: {username}\n🎟️ Tickets: {tickets}\n\n❗️ Confirming will reset all tickets.',
        'lottery_broadcast_prompt': 'Send message to all users?',
        'lottery_enter_message': '✉️ Enter message:',
        'lottery_finished': '✅ Lottery finished.',
        'no_winner': '❌ No winner',
        'tools': '🧰 Tools',
        'lottery': '🎟️ Lottery',
        'insufficient_rights': 'Insufficient rights',
        'back_button': '🔙 Back',
        'user_not_found': '❌ User not found.',
        'assistant_choose_action': 'Choose an action:',
        'assistant_add_button': '➕ Add assistant',
        'assistant_remove_button': '➖ Remove assistant',
        'assistant_add_prompt': 'Send the assistant username:',
        'assistant_remove_prompt': 'Send the username to remove:',
        'assistant_assigned': '✅ Assistant assigned.',
        'assistant_removed': '✅ Assistant removed.',
        'reseller_menu_title': '🤝 Reseller menu',
        'reseller_add_button': '➕ Add reseller',
        'reseller_remove_button': '➖ Remove reseller',
        'reseller_prices_button': '🏷️ Set prices',
        'reseller_enter_username': 'Enter the username:',
        'reseller_already_exists': '⚠️ User is already a reseller.',
        'reseller_added': '✅ Reseller added.',
        'reseller_none': '❌ No resellers found.',
        'reseller_choose': 'Select a reseller:',
        'reseller_confirm_remove': 'Remove {name} from the reseller list?',
        'reseller_removed': '✅ Reseller removed. Reseller pricing disabled.',
        'reseller_main_category_prompt': 'Select a main category:',
        'reseller_category_prompt': 'Select a category:',
        'reseller_subcategory_prompt': 'Select a subcategory:',
        'reseller_item_prompt': 'Select an item:',
        'reseller_category_empty': '❌ No items in this category.',
        'reseller_enter_price': 'Enter the price:',
        'reseller_invalid_price': '⚠️ Invalid price.',
        'reseller_price_set': '✅ Price saved. Choose a main category:',
        'stock_overview_title': '📋 Stock list',
        'stock_choose_category_root': '📦 Choose a category',
        'stock_choose_category': '📂 Choose a category',
        'stock_choose_item': '🏷️ Choose an item',
        'stock_no_items': 'No items available.',
        'stock_item_header': '📦 {item} stock',
        'stock_no_stock': 'No stock available.',
        'stock_not_found': 'Not found.',
        'stock_deleted': '✅ Stock entry deleted.',
        'delete_button': '🗑️ Delete',
        'use_balance_prompt': 'You have {balance}€. Use it to reduce the price?',
        'choose_crypto': 'Choose payment method:',
        'need_top_up': 'You need to top up {missing}€ to complete the purchase. Choose payment method:',
        'item_reserved': '🔒 Item reserved for you for 15 minutes.',
        'payment_cancelled': '✅ Payment cancelled. Reserved items have been released.',
        'top_up_completed': '✅ Top-up completed.',
        'lottery_ticket_awarded': '🎟️ You received a lottery ticket.',
        'lottery_tickets': '🎟️ <b>Lottery tickets</b> — <code>{tickets}</code>',
        'reviews_title': '📝 Review moderation',
        'reviews_menu_pending': '📥 Pending reviews',
        'reviews_menu_approved': '✅ Approved reviews',
        'reviews_menu_rejected': '🚫 Rejected reviews',
        'reviews_none': 'No reviews found in this category.',
        'reviews_list_header': 'Reviews ({status}) — {count}',
        'reviews_not_found': 'Review not found.',
        'review_detail': (
            '<b>Review #{review_id}</b>\n'
            '👤 User: <code>{user}</code>\n'
            '🏷️ Item: {item}\n'
            '⭐ Service: {service}/5\n'
            '🎯 Product: {product}/5\n'
            '💬 Comment: {comment}\n'
            '📌 Status: {status}\n'
            '🕓 Created: {created}'
        ),
        'review_status_pending': 'Pending',
        'review_status_approved': 'Approved',
        'review_status_rejected': 'Rejected',
        'review_approve': '✅ Approve',
        'review_reject': '🚫 Reject',
        'review_status_updated': 'Review status updated.',
        'review_owner_notification': (
            '📝 New review from {user}\n'
            '🏷️ Item: {item}\n'
            '⭐ Service: {service}/5\n'
            '🎯 Product: {product}/5\n'
            '💬 Comment: {comment}'
        ),
        'no_comment_provided': 'No comment provided.',
        'reservations_title': '🗂️ Active reservations — {count}',
        'reservations_none': 'No active reservations right now.',
        'reservations_not_found': 'Reservation not found.',
        'reservation_detail': (
            '<b>Reservation #{reservation_id}</b>\n'
            '👤 User: <code>{user}</code>\n'
            '🏷️ Item: {item}\n'
            '📌 Status: {status}\n'
            '⏱️ Reserved: {reserved_at}\n'
            '⌛ Expires: {expires_at}'
        ),
        'reservation_release': '♻️ Release reservation',
        'reservation_released': 'Reservation released.',
        'reservation_released_notice': 'ℹ️ Reservation for {item} has been released.',
        'manual_payments_title': '💳 Manual payments',
        'manual_payments_prompt_user': 'Send the user ID or @username to credit funds:',
        'manual_payments_prompt_amount': 'Enter the amount in EUR (whole numbers only):',
        'manual_payments_invalid_user': '❌ User not found. Please try again.',
        'manual_payments_invalid_amount': '❌ Invalid amount. Use positive whole numbers.',
        'manual_payments_prompt_note': 'Add a note for this credit (optional):',
        'manual_payments_completed': '✅ Credited {amount}€ to <code>{user}</code>.',
        'manual_payments_history_header': 'Recent manual credits:',
        'manual_payments_history_line': '#{entry_id}: user {user} — {amount}€ (admin {admin})\n📝 {note} ({created})',
        'manual_payments_none': 'No manual payments recorded yet.',
        'manual_payment_user_notice': '💳 Your balance was credited by {amount}€.',
        'manual_payments_add': '➕ Credit user',
        'manual_payments_history': '📜 Payment history',
        'media_title': '🖼️ Media library',
        'media_upload_button': '📤 Upload media',
        'media_list_button': '📚 View assets',
        'media_upload_prompt': 'Send a photo, video, or document to store in the media library.',
        'media_upload_invalid': '❌ Please send a supported media type (photo, video, or document).',
        'media_saved': '✅ Media saved to the library.',
        'media_no_assets': 'No media assets stored yet.',
        'media_list_header': 'Stored media:',
        'media_list_line': '#{asset_id} — {media_type} ({created})',
        'media_detail': (
            '<b>Media #{asset_id}</b>\n'
            '📦 Type: {media_type}\n'
            '🕓 Uploaded: {created}\n'
            '💬 Caption: {caption}'
        ),
        'media_not_found': 'Media asset not found.',
        'media_delete': '🗑️ Delete',
        'media_deleted': 'Media deleted.',
        'media_send': '📨 Send preview',
        'media_send_failed': 'Failed to send media preview.',
        'media_sent': 'Preview sent.',
        'referral_link': '🤝 <b>Referral link</b> — <code>{link}</code>',
        'referrals': '👥 <b>Referrals</b> — {count}',
        'referral_earnings': '💰 <b>Referral earnings</b> — <code>{amount}</code> €',
        'referral_reward': '🎉 Your referral {user} purchased a product — you earned {amount}€!',
        'gift': '🎁 Gift',
        'gift_prompt': 'Who do you want to gift a product to?',
        'gift_user_not_found': '❌ User not found.',
        'gift_select_category': '🎁 Select a product to gift to {user}:',
        'gift_sent': '🎁 Gift sent to {user}!',
        'gift_received': '🎁 You received {item} from {user}!',

        'stock_notify': '📦 Stock alerts',
        'choose_product_notify': 'Select a product to get notified when restocked:',
        'no_out_of_stock': '✅ All products are currently in stock.',
        'stock_subscribed': '🔔 You will be notified when {item} is back in stock.',
        'stock_already_subscribed': 'ℹ️ You are already waiting for {item}.',
        'stock_back_in': '📦 {item} is back in stock!',
        'choose_subcategory': '🏘️ Choose a district:',
        'select_product': '🏪 Select a product',
        'games': '🎮 Games',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Coinflip',
        'achievements': '🏆 Achievements',
        'quests': '🧩 Personalized quests',
        'quests_placeholder': '🔧 Quests are coming soon.',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Coinflip',
        'find_game': '🔍 Find game',
        'create_game': '➕ Create game',
        'play_bot': '🤖 Play against bot',
        'choose_game': 'Choose a game',
        'choose_side': 'Choose side:',
        'enter_bet': 'Enter bet amount:',
        'heads': 'Heads',
        'tails': 'Tails',
        'not_enough_balance': '❌ Not enough balance',
        'win': 'You won {amount}€!',
        'lose': 'You lost {amount}€.',
        'back': '🔙 Back',
        'create': '✅ Create',
        'join': '✅ Join',
        'waiting_opponent': '⏳ Waiting for an opponent...',
        'no_games': '❌ No games available',
        'join_confirm': 'Join {user} for {bet}€ as {side}?',
        'create_confirm': 'Create game for {bet}€ as {side}?',
        'game_cancelled': 'Game cancelled. Bet refunded.',
        'select_room': 'Select a game to join:',
        'achievement_start': 'Write /start in the bot',
        'achievement_first_purchase': 'Make your first purchase',
        'achievement_first_topup': 'Top up your balance',
        'achievement_first_blackjack': 'Play Blackjack',
        'achievement_first_coinflip': 'Play Coinflip',
        'achievement_gift_sent': 'Send a gift',
        'achievement_first_referral': 'Invite a friend',
        'achievement_five_purchases': 'Buy 5 items',
        'achievement_streak_three': '3-day purchase streak',
        'achievement_ten_referrals': 'Refer 10 friends',
        'achievement_unlocked': '🏆 Achievement unlocked: {name}',
        'show_unlocked': 'Show Unlocked',
        'show_locked': 'Show Locked',
        'level_up': '🎉 Congratulations! You reached {level}.',



    },
    'ru': {
        'hello': '👋 Привет, {user}!',
        'balance': '💰 Баланс: {balance} EUR',
        'overpay': '💳 Отправьте точную сумму. Переплаты будут зачислены.',
        'shop': '🛍 Магазин',
        'profile': '👤 Профиль',
        'top_up': '💸 Пополнить',
        'channel': '📢 Канал',
        'price_list': '💲 Прайс-лист',
        'language': '🌐 Язык',
        'admin_panel': '🎛 Админ панель',
        'help': '❓ Помощь',
        'help_info': (
            'Используйте главное меню для работы с ботом:\n'
            '🛍 Магазин – просматривайте категории и выбирайте товар.\n'
            '   • Выберите товар и подтвердите покупку.\n'
            '👤 Профиль – ваш баланс и купленные товары.\n'
            '💸 Пополнить – выберите способ оплаты и следуйте инструкциям.\n'
            '🌐 Язык – сменить язык интерфейса.\n'
            '🎁 Купленные товары – доступны в профиле после покупки.\n'
            'Если нужна помощь, обратитесь к {helper}.'
        ),
        'admin_help_info': (
            'Функции админ-панели:\n'
            '🛠 Назначить ассистентов – управление помощниками.\n'
            '📦 Просмотр склада – список товаров и удаление остатков.\n'
            '🏪 Parduotuvės valdymas – управление магазином.\n'
            '👥 Vartotojų valdymas – управление пользователями.\n'
            '📢 Pranešimų siuntimas – рассылка сообщений.'
        ),
        'assistant_help_info': (
            'Функции панели ассистента:\n'
            '🖼 Привязать фото – добавление фотографий к товарам.\n'
            'Используйте "Назад в меню" для возврата.'
        ),
        'admin_menu_title': '⛩️ Админ-меню',
        'assign_photos_menu': '🖼 Назначить фото',
        'shop_management_menu': '🏪 Управление магазином',
        'information_menu_button': 'ℹ️ Информация',
        'information_menu_title': 'ℹ️ Информационное меню',
        'analytics_button': '📊 Аналитика',
        'shop_management_title': '⛩️ Управление магазином',
        'analytics_title': '📊 Обзор аналитики',
        'analytics_total_revenue': '💰 Общая выручка: {amount}€',
        'analytics_chart_header': 'Продажи ({label})',
        'analytics_period_daily': 'последние 7 дней',
        'analytics_period_weekly': 'еженедельно (4 недели)',
        'analytics_period_monthly': 'ежемесячно (6 месяцев)',
        'analytics_chart_line': '{period}: {bar} {revenue}€ ({orders} заказов)',
        'analytics_no_data': 'Данных пока нет.',
        'analytics_top_cities_header': '🏙️ Топ городов',
        'analytics_unknown_city': 'Неизвестный город',
        'analytics_city_with_region': '{city} ({region})',
        'analytics_group_line': '{name} — {orders} заказов / {revenue}€',
        'analytics_top_types_header': '🏷️ Топ типов товаров',
        'analytics_uncategorized': 'Без категории',
        'analytics_top_products_header': '🔥 Топ товаров',
        'analytics_activity_header': '👥 Активность пользователей',
        'analytics_activity_line_active': '✅ Активных пользователей: {count}',
        'analytics_activity_line_inactive': '⚠️ Неактивных пользователей: {count}',
        'analytics_button_day': 'По дням',
        'analytics_button_week': 'По неделям',
        'analytics_button_month': 'По месяцам',
        'analytics_view_overview': 'Обзор',
        'analytics_view_cities': 'Города',
        'analytics_view_types': 'Типы товаров',
        'analytics_view_products': 'Популярные товары',
        'analytics_view_activity': 'Активность',
        'shop_manage_goods': '📦 Управление товарами',
        'shop_manage_categories': '🗂️ Управление категориями',
        'shop_manage_promos': '🏷️ Промокоды',
        'shop_manage_resellers': '🤝 Реселлеры',
        'shop_manage_broadcast': '📢 Рассылки',
        'shop_manage_stock': '🗄️ Складские инструменты',
        'shop_manage_assistants': '🛠️ Управление ассистентами',
        'information_users': '👥 Управление пользователями',
        'information_logs': '📝 Логи',
        'information_statistics': '📊 Статистика',
        'information_purchases': '🛒 Покупки',
        'information_stock': '📦 Просмотр склада',
        'menu_lottery': '🎟️ Лотерея',
        'menu_reviews': '📝 Отзывы',
        'menu_reservations': '🗂️ Резервации',
        'menu_manual_payments': '💳 Ручные платежи',
        'menu_media': '🖼️ Медиа-библиотека',
        'lottery_view_tickets': '📋 Просмотреть билеты',
        'lottery_run_action': '🎰 Провести лотерею',
        'purchase_view_file': '👁 Посмотреть файл',
        'purchases_choose_date': '📅 Выберите дату',
        'purchases_for_date': '📦 Покупки {date}',
        'purchase_not_found': 'Покупка не найдена.',
        'broadcast_segment_all': 'Все пользователи',
        'broadcast_segment_active': 'Активные пользователи',
        'broadcast_segment_inactive': 'Неактивные пользователи',
        'broadcast_segment_no_activity': 'Без активности',
        'broadcast_segment_resellers': 'Только реселлеры',
        'broadcast_segment_city': 'По городу',
        'broadcast_segment_region': 'По региону',
        'broadcast_choose_segment': 'Выберите получателей рассылки:',
        'broadcast_prompt_message': 'Отправьте сообщение для рассылки:',
        'broadcast_pick_city': 'Выберите город:',
        'broadcast_pick_region': 'Выберите регион:',
        'broadcast_no_cities': 'Города еще не настроены.',
        'broadcast_no_regions': 'Регионы еще не настроены.',
        'broadcast_no_recipients': '❌ Нет получателей для выбранного сегмента.',
        'broadcast_completed': '✅ Рассылка отправлена {count} пользователям.',
        'choose_language': 'Пожалуйста, выберите язык',
        'invoice_message': (
            '🧾 <b>Создан инвойс на оплату</b>\n\n'
            '<b>Сумма:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Адрес оплаты:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Действителен до:</b> {expires_at} LT\n'
            '⚠️ <b>Оплата должна быть выполнена в течение 15 минут после создания.</b>\n\n'
            '❗️ <b>Важно:</b> Отправьте <u>ровно</u> это количество {currency}.\n\n'
            '✅ <b>Подтверждение произойдет автоматически через вебхук после подтверждения сети.</b>'
        ),
        'cancel': 'Отмена',
        'cancel_payment': '❌ Отменить оплату',
        'payment_successful': '✅ Платёж подтверждён. Баланс пополнен на {amount}€',
        'back_home': 'Назад домой',
        'invoice_cancelled': 'Оплата не завершена/истекла. Ваши товары больше не зарезервированы.',
        'total_purchases': '📦 Всего покупок: {count}',
        'streak': '🔥 Серия: {days} дн.',
        'note': '⚠️ Возврат средств невозможен. Отправляйте точную сумму, недоплаты не подтверждаются.',
        'feature_disabled': '❌ Эта функция сейчас отключена.',
        'rate_experience': '⭐ Как вы оцениваете общий опыт?',
        'rate_service': 'Как вы оцениваете качество сервиса?',
        'rate_product': 'Что вы думаете о товаре?',
        'ask_feedback_reason': 'Хотите написать почему?',
        'feedback_reason': 'Пожалуйста, напишите ваш отзыв:',
        'thanks_feedback': 'Спасибо за отзыв!',
        'confirm_purchase': 'Подтвердить покупку {item} за {price}€?',
        'purchase_button': 'Купить',
        'apply_promo': 'Применить промокод',
        'promo_prompt': 'Введите промокод:',
        'promo_invalid': '❌ Недействительный или просроченный промокод',
        'promo_applied': '✅ Промокод применён. Новая цена: {price}€',
        'yes': '✅ Да',
        'no': '❌ Нет',
        'confirm': '✅ Подтвердить',
        'rerun': '🔄 Перезапустить',
        'assign_more': '✅ Фото добавлено. Добавить ещё?',
        'purchased_items': '📦 Купленные товары',
        'purchased_items': '🎁 Купленные товары',
        'back_to_menu': '🔙 Назад в меню',
        'users_tickets': '🎟️ Билеты пользователей:',
        'no_tickets': 'Нет билетов',
        'lottery_winner': '🎉 Победитель: {username}\n🎟️ Билеты: {tickets}\n\n❗️ Подтверждение сбросит все билеты.',
        'lottery_broadcast_prompt': 'Отправить сообщение всем пользователям?',
        'lottery_enter_message': '✉️ Введите сообщение:',
        'lottery_finished': '✅ Лотерея завершена.',
        'no_winner': '❌ Нет победителя',
        'tools': '🧰 Инструменты',
        'lottery': '🎟️ Лотерея',
        'insufficient_rights': 'Недостаточно прав',
        'back_button': '🔙 Назад',
        'user_not_found': '❌ Пользователь не найден.',
        'assistant_choose_action': 'Выберите действие:',
        'assistant_add_button': '➕ Добавить ассистента',
        'assistant_remove_button': '➖ Удалить ассистента',
        'assistant_add_prompt': 'Отправьте имя пользователя ассистента:',
        'assistant_remove_prompt': 'Отправьте имя пользователя для удаления:',
        'assistant_assigned': '✅ Ассистент назначен.',
        'assistant_removed': '✅ Ассистент удалён.',
        'reseller_menu_title': '🤝 Меню реселлеров',
        'reseller_add_button': '➕ Добавить реселлера',
        'reseller_remove_button': '➖ Удалить реселлера',
        'reseller_prices_button': '🏷️ Настроить цены',
        'reseller_enter_username': 'Введите имя пользователя:',
        'reseller_already_exists': '⚠️ Пользователь уже является реселлером.',
        'reseller_added': '✅ Реселлер добавлен.',
        'reseller_none': '❌ Реселлеры отсутствуют.',
        'reseller_choose': 'Выберите реселлера:',
        'reseller_confirm_remove': 'Удалить {name} из списка реселлеров?',
        'reseller_removed': '✅ Реселлер удалён. Цены для реселлеров отключены.',
        'reseller_main_category_prompt': 'Выберите основную категорию:',
        'reseller_category_prompt': 'Выберите категорию:',
        'reseller_subcategory_prompt': 'Выберите подкатегорию:',
        'reseller_item_prompt': 'Выберите товар:',
        'reseller_category_empty': '❌ В этой категории нет товаров.',
        'reseller_enter_price': 'Введите цену:',
        'reseller_invalid_price': '⚠️ Некорректная цена.',
        'reseller_price_set': '✅ Цена сохранена. Выберите основную категорию:',
        'stock_overview_title': '📋 Список остатков',
        'stock_choose_category_root': '📦 Выберите категорию',
        'stock_choose_category': '📂 Выберите категорию',
        'stock_choose_item': '🏷️ Выберите товар',
        'stock_no_items': 'Товары отсутствуют.',
        'stock_item_header': '📦 Остатки {item}',
        'stock_no_stock': 'Остатков нет.',
        'stock_not_found': 'Не найдено.',
        'stock_deleted': '✅ Остаток удалён.',
        'delete_button': '🗑️ Удалить',
        'use_balance_prompt': 'У вас {balance}€. Использовать их для снижения цены?',
        'choose_crypto': 'Выберите способ оплаты:',
        'need_top_up': 'Вам нужно пополнить {missing}€ для покупки. Выберите способ оплаты:',
        'item_reserved': '🔒 Товар зарезервирован для вас на 15 минут.',
        'payment_cancelled': '✅ Платёж отменён. Резерв снят.',
        'top_up_completed': '✅ Пополнение завершено.',
        'lottery_ticket_awarded': '🎟️ Вы получили лотерейный билет.',
        'lottery_tickets': '🎟️ <b>Лотерейные билеты</b> — <code>{tickets}</code>',
        'reviews_title': '📝 Модерация отзывов',
        'reviews_menu_pending': '📥 Ожидающие отзывы',
        'reviews_menu_approved': '✅ Одобренные отзывы',
        'reviews_menu_rejected': '🚫 Отклонённые отзывы',
        'reviews_none': 'В этой категории нет отзывов.',
        'reviews_list_header': 'Отзывы ({status}) — {count}',
        'reviews_not_found': 'Отзыв не найден.',
        'review_detail': (
            '<b>Отзыв #{review_id}</b>\n'
            '👤 Пользователь: <code>{user}</code>\n'
            '🏷️ Товар: {item}\n'
            '⭐ Сервис: {service}/5\n'
            '🎯 Товар: {product}/5\n'
            '💬 Комментарий: {comment}\n'
            '📌 Статус: {status}\n'
            '🕓 Создан: {created}'
        ),
        'review_status_pending': 'Ожидает',
        'review_status_approved': 'Одобрен',
        'review_status_rejected': 'Отклонён',
        'review_approve': '✅ Одобрить',
        'review_reject': '🚫 Отклонить',
        'review_status_updated': 'Статус отзыва обновлён.',
        'review_owner_notification': (
            '📝 Новый отзыв от {user}\n'
            '🏷️ Товар: {item}\n'
            '⭐ Сервис: {service}/5\n'
            '🎯 Товар: {product}/5\n'
            '💬 Комментарий: {comment}'
        ),
        'no_comment_provided': 'Комментарий отсутствует.',
        'reservations_title': '🗂️ Активные резервации — {count}',
        'reservations_none': 'Нет активных резерваций.',
        'reservations_not_found': 'Резервация не найдена.',
        'reservation_detail': (
            '<b>Резервация #{reservation_id}</b>\n'
            '👤 Пользователь: <code>{user}</code>\n'
            '🏷️ Товар: {item}\n'
            '📌 Статус: {status}\n'
            '⏱️ Забронировано: {reserved_at}\n'
            '⌛ Истекает: {expires_at}'
        ),
        'reservation_release': '♻️ Освободить резервацию',
        'reservation_released': 'Резервация освобождена.',
        'reservation_released_notice': 'ℹ️ Резервация для {item} была снята.',
        'manual_payments_title': '💳 Ручные платежи',
        'manual_payments_prompt_user': 'Отправьте ID или @username пользователя для начисления:',
        'manual_payments_prompt_amount': 'Введите сумму в EUR (только целые числа):',
        'manual_payments_invalid_user': '❌ Пользователь не найден. Попробуйте ещё раз.',
        'manual_payments_invalid_amount': '❌ Некорректная сумма. Используйте положительные целые значения.',
        'manual_payments_prompt_note': 'Добавьте примечание к начислению (необязательно):',
        'manual_payments_completed': '✅ Начислено {amount}€ пользователю <code>{user}</code>.',
        'manual_payments_history_header': 'История ручных начислений:',
        'manual_payments_history_line': '#{entry_id}: пользователь {user} — {amount}€ (админ {admin})\n📝 {note} ({created})',
        'manual_payments_none': 'Ручных начислений пока нет.',
        'manual_payment_user_notice': '💳 Ваш баланс пополнен на {amount}€.',
        'manual_payments_add': '➕ Начислить пользователю',
        'manual_payments_history': '📜 История начислений',
        'media_title': '🖼️ Медиа-библиотека',
        'media_upload_button': '📤 Загрузить медиа',
        'media_list_button': '📚 Список файлов',
        'media_upload_prompt': 'Отправьте фото, видео или документ для сохранения.',
        'media_upload_invalid': '❌ Отправьте поддерживаемый тип медиа (фото, видео или документ).',
        'media_saved': '✅ Медиафайл сохранён.',
        'media_no_assets': 'Медиафайлов пока нет.',
        'media_list_header': 'Сохранённые медиа:',
        'media_list_line': '#{asset_id} — {media_type} ({created})',
        'media_detail': (
            '<b>Медиа #{asset_id}</b>\n'
            '📦 Тип: {media_type}\n'
            '🕓 Загружено: {created}\n'
            '💬 Подпись: {caption}'
        ),
        'media_not_found': 'Медиафайл не найден.',
        'media_delete': '🗑️ Удалить',
        'media_deleted': 'Медиафайл удалён.',
        'media_send': '📨 Отправить предпросмотр',
        'media_send_failed': 'Не удалось отправить предпросмотр.',
        'media_sent': 'Предпросмотр отправлен.',
        'referral_link': '🤝 <b>Реферальная ссылка</b> — <code>{link}</code>',
        'referrals': '👥 <b>Рефералы</b> — {count}',
        'referral_earnings': '💰 <b>Заработок с рефералов</b> — <code>{amount}</code> €',
        'referral_reward': '🎉 Ваш реферал {user} совершил покупку — вы получили {amount}€!',
        'gift': '🎁 Подарок',
        'gift_prompt': 'Кому вы хотите подарить товар?',
        'gift_user_not_found': '❌ Пользователь не найден.',
        'gift_select_category': '🎁 Выберите товар для подарка пользователю {user}:',
        'gift_sent': '🎁 Подарок отправлен пользователю {user}!',
        'gift_received': '🎁 Вы получили {item} от {user}!',
        'stock_notify': '📦 Уведомления о наличии',
        'choose_product_notify': 'Выберите товар для уведомления о появлении:',
        'no_out_of_stock': '✅ Все товары в наличии.',
        'stock_subscribed': '🔔 Мы уведомим вас, когда {item} появится.',
        'stock_already_subscribed': 'ℹ️ Вы уже ожидаете {item}.',
        'stock_back_in': '📦 {item} снова в наличии!',

        'choose_subcategory': '🏘️ Выберите район:',
        'select_product': '🏪 Выберите товар',
        'games': '🎮 Игры',
        'blackjack': '🃏 Блэкджек',
        'coinflip': '🪙 Монетка',
        'achievements': '🏆 Достижения',
        'quests': '🧩 Персональные задания',
        'quests_placeholder': '🔧 Задания скоро появятся.',
        'find_game': '🔍 Найти игру',
        'create_game': '➕ Создать игру',
        'play_bot': '🤖 Играть с ботом',
        'choose_game': 'Выберите игру',
        'choose_side': 'Выберите сторону:',
        'enter_bet': 'Введите сумму ставки:',
        'heads': 'Орел',
        'tails': 'Решка',
        'not_enough_balance': '❌ Недостаточно средств',
        'win': 'Вы выиграли {amount}€!',
        'lose': 'Вы проиграли {amount}€.',
        'back': '🔙 Назад',
        'create': '✅ Создать',
        'join': '✅ Присоединиться',
        'waiting_opponent': '⏳ Ожидание оппонента...',
        'no_games': '❌ Нет доступных игр',
        'join_confirm': 'Играть с {user} на {bet}€ за {side}?',
        'create_confirm': 'Создать игру на {bet}€ за {side}?',
        'game_cancelled': 'Игра отменена. Ставка возвращена.',
        'select_room': 'Выберите игру для присоединения:',
        'achievement_start': 'Напишите /start боту',
        'achievement_first_purchase': 'Совершите первую покупку',
        'achievement_first_topup': 'Пополните баланс',

        'achievement_first_blackjack': 'Сыграйте в Блэкджек',
        'achievement_first_coinflip': 'Сыграйте в Монетку',
        'achievement_gift_sent': 'Отправьте подарок',
        'achievement_first_referral': 'Пригласите друга',
        'achievement_five_purchases': 'Купите 5 товаров',
        'achievement_streak_three': 'Покупайте 3 дня подряд',
        'achievement_ten_referrals': 'Пригласите 10 друзей',
        'achievement_unlocked': '🏆 Достижение получено: {name}',
        'show_unlocked': 'Показать полученные',
        'show_locked': 'Показать неполученные',
        'level_up': '🎉 Поздравляем! Вы достигли уровня {level}.',

    },
    'lt': {
        'hello': '👋 Sveiki, {user}!',
        'balance': '💰 Balansas: {balance} EUR',
        'overpay': '💳 Siųskite tikslią sumą. Permokos bus įskaitytos.',
        'shop': '🛍 Parduotuvė',
        'profile': '👤 Profilis',
        'top_up': '💸 Papildyti',
        'channel': '📢 Kanalas',
        'price_list': '💲 Kainoraštis',
        'language': '🌐 Kalba',
        'admin_panel': '🎛 Admin pultas',
        'help': '❓ Pagalba',
        'help_info': (
            'Naudokite pagrindinį meniu darbui su botu:\n'
            '🛍 Parduotuvė – naršykite kategorijas ir pasirinkite prekę.\n'
            '   • Pasirinkite prekę ir patvirtinkite pirkimą.\n'
            '👤 Profilis – jūsų balansas ir nupirktos prekės.\n'
            '💸 Papildyti – pasirinkite mokėjimo būdą ir vykdykite instrukcijas.\n'
            '🌐 Kalba – pakeisti sąsajos kalbą.\n'
            '🎁 Nupirktos prekės – matomos profilyje po pirkimo.\n'
            'Jei reikia pagalbos, susisiekite su {helper}.'
        ),
        'admin_help_info': (
            'Admin pulto funkcijos:\n'
            '🛠 Asistentų priskyrimas – valdykite asistentų paskyras.\n'
            '📦 Peržiūrėti likučius – naršykite prekes ir trinkite likučius.\n'
            '🏪 Parduotuvės valdymas – prekių ir kategorijų valdymas.\n'
            '👥 Vartotojų valdymas – naudotojų balansai ir rolės.\n'
            '📢 Pranešimų siuntimas – siųsti žinutes vartotojams.'
        ),
        'assistant_help_info': (
            'Asistento pulto funkcijos:\n'
            '🖼 Nuotraukų priskyrimas – pridėkite nuotraukas prie prekių.\n'
            'Naudokite „Atgal į meniu“ norėdami grįžti.'
        ),
        'admin_menu_title': '⛩️ Administratoriaus meniu',
        'assign_photos_menu': '🖼 Priskirti nuotraukas',
        'shop_management_menu': '🏪 Parduotuvės valdymas',
        'information_menu_button': 'ℹ️ Informacija',
        'information_menu_title': 'ℹ️ Informacijos meniu',
        'analytics_button': '📊 Analitika',
        'shop_management_title': '⛩️ Parduotuvės valdymas',
        'analytics_title': '📊 Analitikos suvestinė',
        'analytics_total_revenue': '💰 Bendra apyvarta: {amount}€',
        'analytics_chart_header': 'Pardavimai ({label})',
        'analytics_period_daily': 'paskutinės 7 dienos',
        'analytics_period_weekly': 'kas savaitę (4 savaitės)',
        'analytics_period_monthly': 'kas mėnesį (6 mėnesiai)',
        'analytics_chart_line': '{period}: {bar} {revenue}€ ({orders} užsakymų)',
        'analytics_no_data': 'Kol kas nėra duomenų.',
        'analytics_top_cities_header': '🏙️ Populiariausi miestai',
        'analytics_unknown_city': 'Nežinomas miestas',
        'analytics_city_with_region': '{city} ({region})',
        'analytics_group_line': '{name} — {orders} užsakymų / {revenue}€',
        'analytics_top_types_header': '🏷️ Populiariausios prekių rūšys',
        'analytics_uncategorized': 'Be kategorijos',
        'analytics_top_products_header': '🔥 Populiariausios prekės',
        'analytics_activity_header': '👥 Vartotojų aktyvumas',
        'analytics_activity_line_active': '✅ Aktyvūs vartotojai: {count}',
        'analytics_activity_line_inactive': '⚠️ Neaktyvūs vartotojai: {count}',
        'analytics_button_day': 'Dienos',
        'analytics_button_week': 'Savaitės',
        'analytics_button_month': 'Mėnesiai',
        'analytics_view_overview': 'Apžvalga',
        'analytics_view_cities': 'Miestai',
        'analytics_view_types': 'Prekių tipai',
        'analytics_view_products': 'Populiarios prekės',
        'analytics_view_activity': 'Aktyvumas',
        'shop_manage_goods': '📦 Valdyti prekes',
        'shop_manage_categories': '🗂️ Valdyti kategorijas',
        'shop_manage_promos': '🏷️ Nuolaidų kodai',
        'shop_manage_resellers': '🤝 Reselleriai',
        'shop_manage_broadcast': '📢 Pranešimų siuntimas',
        'shop_manage_stock': '🗄️ Atsargų įrankiai',
        'shop_manage_assistants': '🛠️ Asistentų valdymas',
        'information_users': '👥 Vartotojų valdymas',
        'information_logs': '📝 Žurnalai',
        'information_statistics': '📊 Statistika',
        'information_purchases': '🛒 Pirkimai',
        'information_stock': '📦 Peržiūrėti atsargas',
        'menu_lottery': '🎟️ Loterija',
        'menu_reviews': '📝 Atsiliepimai',
        'menu_reservations': '🗂️ Rezervacijos',
        'menu_manual_payments': '💳 Rankiniai mokėjimai',
        'menu_media': '🖼️ Medijų biblioteka',
        'lottery_view_tickets': '📋 Peržiūrėti bilietus',
        'lottery_run_action': '🎰 Vykdyti loteriją',
        'purchase_view_file': '👁 Peržiūrėti failą',
        'purchases_choose_date': '📅 Pasirinkite datą',
        'purchases_for_date': '📦 Pirkimai {date}',
        'purchase_not_found': 'Pirkimas nerastas.',
        'broadcast_segment_all': 'Visi vartotojai',
        'broadcast_segment_active': 'Aktyvūs vartotojai',
        'broadcast_segment_inactive': 'Neaktyvūs vartotojai',
        'broadcast_segment_no_activity': 'Be aktyvumo',
        'broadcast_segment_resellers': 'Tik reselleriai',
        'broadcast_segment_city': 'Pagal miestą',
        'broadcast_segment_region': 'Pagal regioną',
        'broadcast_choose_segment': 'Pasirinkite kam siųsti pranešimą:',
        'broadcast_prompt_message': 'Įveskite žinutę transliacijai:',
        'broadcast_pick_city': 'Pasirinkite miestą:',
        'broadcast_pick_region': 'Pasirinkite regioną:',
        'broadcast_no_cities': 'Miestai dar nesukonfigūruoti.',
        'broadcast_no_regions': 'Regionai dar nesukonfigūruoti.',
        'broadcast_no_recipients': '❌ Pasirinktai auditorijai vartotojų nėra.',
        'broadcast_completed': '✅ Pranešimas išsiųstas {count} vartotojams.',
        'choose_language': 'Pasirinkite kalbą',
        'invoice_message': (
            '🧾 <b>Sukurta mokėjimo sąskaita</b>\n\n'
            '<b>Suma:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Mokėjimo adresas:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Galioja iki:</b> {expires_at} LT\n'
            '⚠️ <b>Mokėjimą reikia atlikti per 15 minučių nuo sąskaitos sukūrimo.</b>\n\n'
            '❗️ <b>Svarbu:</b> Nusiųskite <u>tiksliai</u> tiek {currency} į šį adresą.\n\n'
            '✅ <b>Patvirtinimas vyks automatiškai per webhook po tinklo patvirtinimo.</b>'
        ),
        'cancel': 'Atšaukti',
        'cancel_payment': '❌ Atšaukti mokėjimą',
        'payment_successful': '✅ Mokėjimas patvirtintas. Balansas padidintas {amount}€',
        'back_home': 'Grįžti į pradžią',
        'invoice_cancelled': 'Mokėjimas nepavyko/baigėsi. Jūsų prekės nebėra rezervuotos.',
        'total_purchases': '📦 Viso pirkinių: {count}',
        'streak': '🔥 Serija: {days} d.',
        'note': '⚠️ Pastaba: grąžinimų nėra. Įsitikinkite, kad siunčiate tikslią sumą, nes nepakankamos sumos nebus patvirtintos.',
        'feature_disabled': '❌ Ši funkcija šiuo metu išjungta.',
        'rate_experience': '⭐ Kaip vertinate bendrą patirtį?',
        'rate_service': 'Kaip vertinate aptarnavimo kokybę?',
        'rate_product': 'Kokia jūsų nuomonė apie produktą?',
        'ask_feedback_reason': 'Ar norėtumėte parašyti kodėl?',
        'feedback_reason': 'Prašome parašyti atsiliepimą:',
        'thanks_feedback': 'Ačiū už atsiliepimą!',
        'confirm_purchase': 'Patvirtinti {item} pirkimą už {price}€?',
        'purchase_button': 'Pirkti',
        'apply_promo': 'Taikyti nuolaidos kodą',
        'promo_prompt': 'Įveskite nuolaidos kodą:',
        'promo_invalid': '❌ Neteisingas arba pasibaigęs kodas',
        'promo_applied': '✅ Kodas pritaikytas. Nauja kaina: {price}€',
        'yes': '✅ Taip',
        'no': '❌ Ne',
        'confirm': '✅ Patvirtinti',
        'rerun': '🔄 Perleisti',
        'assign_more': '✅ Nuotrauka pridėta. Pridėti dar?',
        'purchased_items': '📦 Įsigytos prekės',
        'purchased_items': '🎁 Įsigytos prekės',
        'back_to_menu': '🔙 Atgal į meniu',
        'users_tickets': '🎟️ Vartotojų bilietai:',
        'no_tickets': 'Nėra bilietų',
        'lottery_winner': '🎉 Nugalėtojas: {username}\n🎟️ Bilietai: {tickets}\n\n❗️ Patvirtinus, visi bilietai bus ištrinti.',
        'lottery_broadcast_prompt': 'Siųsti pranešimą visiems vartotojams?',
        'lottery_enter_message': '✉️ Įveskite pranešimą:',
        'lottery_finished': '✅ Loterija baigta.',
        'no_winner': '❌ Nėra nugalėtojo',
        'tools': '🧰 Įrankiai',
        'lottery': '🎟️ Loterija',
        'insufficient_rights': 'Nepakanka teisių',
        'back_button': '🔙 Grįžti atgal',
        'user_not_found': '❌ Vartotojas nerastas.',
        'assistant_choose_action': 'Pasirinkite veiksmą:',
        'assistant_add_button': '➕ Pridėti asistentą',
        'assistant_remove_button': '➖ Pašalinti asistentą',
        'assistant_add_prompt': 'Siųskite asistento vartotojo vardą:',
        'assistant_remove_prompt': 'Siųskite pašalinamo vartotojo vardą:',
        'assistant_assigned': '✅ Asistentas priskirtas.',
        'assistant_removed': '✅ Asistentas pašalintas.',
        'reseller_menu_title': '🤝 Resellerių meniu',
        'reseller_add_button': '➕ Pridėti resellerį',
        'reseller_remove_button': '➖ Išimti resellerį',
        'reseller_prices_button': '🏷️ Taikyti kainas',
        'reseller_enter_username': 'Įveskite vartotojo vardą:',
        'reseller_already_exists': '⚠️ Vartotojas jau yra reselleris.',
        'reseller_added': '✅ Reselleris pridėtas.',
        'reseller_none': '❌ Nėra resellerių.',
        'reseller_choose': 'Pasirinkite resellerį:',
        'reseller_confirm_remove': 'Pašalinti {name} iš resellerių sąrašo?',
        'reseller_removed': '✅ Reselleris pašalintas. Jam nebetaikoma resellerio kaina.',
        'reseller_main_category_prompt': 'Pasirinkite pagrindinę kategoriją:',
        'reseller_category_prompt': 'Pasirinkite kategoriją:',
        'reseller_subcategory_prompt': 'Pasirinkite subkategoriją:',
        'reseller_item_prompt': 'Pasirinkite prekę:',
        'reseller_category_empty': '❌ Šioje kategorijoje nėra prekių.',
        'reseller_enter_price': 'Įveskite kainą:',
        'reseller_invalid_price': '⚠️ Neteisinga kaina.',
        'reseller_price_set': '✅ Kaina nustatyta. Pasirinkite pagrindinę kategoriją:',
        'stock_overview_title': '📋 Atsargų sąrašas',
        'stock_choose_category_root': '📦 Pasirinkite kategoriją',
        'stock_choose_category': '📂 Pasirinkite kategoriją',
        'stock_choose_item': '🏷 Pasirinkite prekę',
        'stock_no_items': 'Prekių nėra.',
        'stock_item_header': '📦 {item} atsargos',
        'stock_no_stock': 'Nėra atsargų.',
        'stock_not_found': 'Nerasta.',
        'stock_deleted': '✅ Atsargos ištrintos.',
        'delete_button': '🗑️ Ištrinti',
        'use_balance_prompt': 'Turite {balance}€. Panaudoti juos kainai sumažinti?',
        'choose_crypto': 'Pasirinkite mokėjimo būdą:',
        'need_top_up': 'Turite papildyti {missing}€ šiam pirkiniui. Pasirinkite mokėjimo būdą:',
        'item_reserved': '🔒 Prekė rezervuota jums 15 minučių.',
        'payment_cancelled': '✅ Mokėjimas atšauktas. Rezervuotos prekės atlaisvintos.',
        'top_up_completed': '✅ Papildymas baigtas.',
        'lottery_ticket_awarded': '🎟️ Gavote loterijos bilietą.',
        'lottery_tickets': '🎟️ <b>Loterijos bilietai</b> — <code>{tickets}</code>',
        'reviews_title': '📝 Atsiliepimų moderavimas',
        'reviews_menu_pending': '📥 Laukiantys atsiliepimai',
        'reviews_menu_approved': '✅ Patvirtinti atsiliepimai',
        'reviews_menu_rejected': '🚫 Atmesti atsiliepimai',
        'reviews_none': 'Šioje kategorijoje nėra atsiliepimų.',
        'reviews_list_header': 'Atsiliepimai ({status}) — {count}',
        'reviews_not_found': 'Atsiliepimas nerastas.',
        'review_detail': (
            '<b>Atsiliepimas #{review_id}</b>\n'
            '👤 Vartotojas: <code>{user}</code>\n'
            '🏷️ Prekė: {item}\n'
            '⭐ Aptarnavimas: {service}/5\n'
            '🎯 Produktas: {product}/5\n'
            '💬 Komentaras: {comment}\n'
            '📌 Būsena: {status}\n'
            '🕓 Sukurta: {created}'
        ),
        'review_status_pending': 'Laukia',
        'review_status_approved': 'Patvirtintas',
        'review_status_rejected': 'Atmestas',
        'review_approve': '✅ Patvirtinti',
        'review_reject': '🚫 Atmesti',
        'review_status_updated': 'Atsiliepimo būsena atnaujinta.',
        'review_owner_notification': (
            '📝 Naujas atsiliepimas nuo {user}\n'
            '🏷️ Prekė: {item}\n'
            '⭐ Aptarnavimas: {service}/5\n'
            '🎯 Produktas: {product}/5\n'
            '💬 Komentaras: {comment}'
        ),
        'no_comment_provided': 'Komentaras nepateiktas.',
        'reservations_title': '🗂️ Aktyvios rezervacijos — {count}',
        'reservations_none': 'Aktyvių rezervacijų nėra.',
        'reservations_not_found': 'Rezervacija nerasta.',
        'reservation_detail': (
            '<b>Rezervacija #{reservation_id}</b>\n'
            '👤 Vartotojas: <code>{user}</code>\n'
            '🏷️ Prekė: {item}\n'
            '📌 Būsena: {status}\n'
            '⏱️ Rezervuota: {reserved_at}\n'
            '⌛ Galioja iki: {expires_at}'
        ),
        'reservation_release': '♻️ Atlaisvinti rezervaciją',
        'reservation_released': 'Rezervacija atlaisvinta.',
        'reservation_released_notice': 'ℹ️ Rezervacija dėl {item} buvo atšaukta.',
        'manual_payments_title': '💳 Rankiniai mokėjimai',
        'manual_payments_prompt_user': 'Įrašykite vartotojo ID arba @vardą balansui papildyti:',
        'manual_payments_prompt_amount': 'Įveskite sumą EUR (tik sveiki skaičiai):',
        'manual_payments_invalid_user': '❌ Vartotojas nerastas. Bandykite dar kartą.',
        'manual_payments_invalid_amount': '❌ Neteisinga suma. Naudokite teigiamus sveikus skaičius.',
        'manual_payments_prompt_note': 'Pridėkite pastabą (nebūtina):',
        'manual_payments_completed': '✅ Papildyta {amount}€ vartotojui <code>{user}</code>.',
        'manual_payments_history_header': 'Rankinių papildymų istorija:',
        'manual_payments_history_line': '#{entry_id}: vartotojas {user} — {amount}€ (administratorius {admin})\n📝 {note} ({created})',
        'manual_payments_none': 'Rankinių papildymų dar nėra.',
        'manual_payment_user_notice': '💳 Jūsų balansas papildytas {amount}€.',
        'manual_payments_add': '➕ Papildyti vartotoją',
        'manual_payments_history': '📜 Papildymų istorija',
        'media_title': '🖼️ Medijų biblioteka',
        'media_upload_button': '📤 Įkelti mediją',
        'media_list_button': '📚 Failų sąrašas',
        'media_upload_prompt': 'Atsiųskite nuotrauką, vaizdo įrašą ar dokumentą išsaugojimui.',
        'media_upload_invalid': '❌ Siųskite palaikomą medijos tipą (nuotrauką, vaizdo įrašą ar dokumentą).',
        'media_saved': '✅ Medija išsaugota.',
        'media_no_assets': 'Medijų dar nėra.',
        'media_list_header': 'Išsaugotos medijos:',
        'media_list_line': '#{asset_id} — {media_type} ({created})',
        'media_detail': (
            '<b>Medija #{asset_id}</b>\n'
            '📦 Tipas: {media_type}\n'
            '🕓 Įkelta: {created}\n'
            '💬 Aprašas: {caption}'
        ),
        'media_not_found': 'Medija nerasta.',
        'media_delete': '🗑️ Ištrinti',
        'media_deleted': 'Medija ištrinta.',
        'media_send': '📨 Siųsti peržiūrą',
        'media_send_failed': 'Nepavyko išsiųsti peržiūros.',
        'media_sent': 'Peržiūra išsiųsta.',
        'referral_link': '🤝 <b>Pakvietimo nuoroda</b> — <code>{link}</code>',
        'referrals': '👥 <b>Pakviesti vartotojai</b> — {count}',
        'referral_earnings': '💰 <b>Uždirbta iš pakvietimų</b> — <code>{amount}</code> €',
        'referral_reward': '🎉 Jūsų pakviestas vartotojas {user} įsigijo prekę – gavote {amount}€!',
        'gift': '🎁 Dovana',
        'gift_prompt': 'Kam norite padovanoti produktą?',
        'gift_user_not_found': '❌ Vartotojas nerastas.',
        'gift_select_category': '🎁 Pasirinkite produktą dovanai naudotojui {user}:',
        'gift_sent': '🎁 Dovana išsiųsta naudotojui {user}!',
        'gift_received': '🎁 Gavote {item} nuo {user}!',

        'stock_notify': '📦 Atsargų pranešimai',
        'choose_product_notify': 'Pasirinkite prekę, kurios atsargų laukti:',
        'no_out_of_stock': '✅ Visos prekės turimos.',
        'stock_subscribed': '🔔 Būsite informuoti, kai {item} bus papildyta.',
        'stock_already_subscribed': 'ℹ️ Jūs jau laukiate {item}.',
        'stock_back_in': '📦 {item} vėl sandėlyje!',

        'choose_subcategory': '🏘️ Pasirinkite rajoną:',
        'select_product': '🏪 Pasirinkite prekę',
        'games': '🎮 Žaidimai',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Monetos metimas',
        'achievements': '🏆 Pasiekimai',
        'quests': '🧩 Asmeniniai uždaviniai',
        'quests_placeholder': '🔧 Uždaviniai greitai atsiras.',
        'find_game': '🔍 Rasti žaidimą',
        'create_game': '➕ Sukurti žaidimą',
        'play_bot': '🤖 Žaisti su botu',
        'choose_game': 'Pasirinkite žaidimą',
        'choose_side': 'Pasirinkite pusę:',
        'enter_bet': 'Įveskite statymo sumą:',
        'heads': 'Herbas',
        'tails': 'Skaičius',
        'not_enough_balance': '❌ Nepakanka lėšų',
        'win': 'Laimėjote {amount}€!',
        'lose': 'Pralaimėjote {amount}€.',
        'back': '🔙 Atgal',
        'create': '✅ Sukurti',
        'join': '✅ Prisijungti',
        'waiting_opponent': '⏳ Laukiama priešininko...',
        'no_games': '❌ Nėra žaidimų',
        'join_confirm': 'Žaisti prieš {user} už {bet}€ kaip {side}?',
        'create_confirm': 'Sukurti žaidimą už {bet}€ kaip {side}?',
        'game_cancelled': 'Žaidimas atšauktas. Statymas grąžintas.',
        'select_room': 'Pasirinkite žaidimą prisijungti:',
        'achievement_start': 'Parašykite /start botui',
        'achievement_first_purchase': 'Atlikite pirmą pirkimą',
        'achievement_first_topup': 'Papildykite balansą',
        'achievement_first_blackjack': 'Sužaiskite Blackjack',
        'achievement_first_coinflip': 'Sužaiskite monetą',
        'achievement_gift_sent': 'Išsiųskite dovaną',
        'achievement_first_referral': 'Pakvieskite draugą',
        'achievement_five_purchases': 'Nupirkite 5 prekes',
        'achievement_streak_three': '3 dienų pirkimų serija',
        'achievement_ten_referrals': 'Pakvieskite 10 draugų',
        'achievement_unlocked': '🏆 Pasiekimas atrakintas: {name}',
        'show_unlocked': 'Rodyti pasiektus',
        'show_locked': 'Rodyti nepasiektus',
        'level_up': '🎉 Sveikiname! Pasiekėte {level}.',


        'achievement_unlocked': '🏆 Pasiekimas atrakintas: {name}',




    },
}

def t(lang: str, key: str, **kwargs) -> str:
    lang_data = LANGUAGES.get(lang, LANGUAGES['en'])
    template = lang_data.get(key, '')
    return template.format(**kwargs)
